spring.web.error.include-binding-errors=always
spring.web.error.include-message=always
spring.web.error.include-stacktrace=on_param
server.port=${SERVER_PORT:8080}
spring.application.name=Shop
spring.datasource.username=${DATASOURCE_USERNAME:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:postgres}
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/shopdb}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contecxtual_creation=true
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.open-in-view=false
spring.mail.host=${MAIL_HOST:smtp.example.com}
spring.mail.port=${MAIL_PORT:111}
spring.mail.username=${MAIL_USERNAME:smtp.example.com}
spring.mail.password=${MAIL_PASSWORD:smtp.example.com}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
springdoc.api-docs.enabled=false
springdoc.api-docs.path=/api/v3/api-docs
springdoc.swagger-ui.path=/api/swagger-ui.html
#springdoc.swagger-ui.config-url=/api/v3/api-docs/swagger-config
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.url=/api/open-api.yml
jwt.secret-key=${JWT_SECRET_KEY:9a4f2c8d3e1b7a6f5c4d3e2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a21+}
jwt.issuer=${JWT_ISSUER:shop-api}
jwt.access-ttl-minutes=${JWT_ACCESS_TTL_MINUTES:15}
jwt.refresh-ttl-days=${JWT_REFRESH_TTL_DAYS:30}

# ZarinPal Configuration
zarinpal.merchant-id=${ZARINPAL_MERCHANT_ID:1344b5d4-0048-11e8-94db-005056a205be}
zarinpal.sandbox=${ZARINPAL_SANDBOX:true}
zarinpal.access-token=${ZARINPAL_ACCESS_TOKEN:dfsdfds}
app.ngrok-url=${NGROK_URL:https://womb-nearly-justify.ngrok-free.dev}