openapi: 3.0.1
info:
  title: Shopping RESTful API V1
  description: |-
    This API exposes RESTful authentication and authorisation  via JWT.
#  license:
#    name: MIT License
#    url: https://github.com/puriakazemieh/Shop-Kotlin-Spring-Boot/LICENSE.txt
  version: 1.0.0
servers:
  - url: http://localhost:9000
    description: DEVELOPMENT
  - url: https://kazemieh.com
    description: PRODUCTION
security:
  - BearerAuth: [ ]

